### ISSUE TITLE
Missing collider .obj files

### ISSUE THREAD

**Issue by inequation** [wyegelwel/snow#16]
Hey there,

I found this implementation of the Disney paper on the internet and wanted to take a look. :) I've got it to build under Windows and VS2013 (see my fork), but there seems to be a `data` subdirectory that's missing from the repo. There are two hardcoded paths:

```
  D:\projects\snow\project\scene\scenecollider.cpp(86):        OBJParser::load( PROJECT_PATH "/data/models/sphereCol.obj", colliderMeshes );
  D:\projects\snow\project\scene\scenecollider.cpp(89):        OBJParser::load( PROJECT_PATH "/data/models/plane.obj", colliderMeshes );
```

These files can't be big, so it'd be cool if you could upload them. That is, if you still have them – I know what it's like with these university projects. ;)

Regards,

Leszek

**Comment by ericjang** [comment]
Done! They are in `data/models`. I've also added a number of other OBJ files in that folder that can be loaded as snow-containing volumes / test scenes. The `data/scenes` folder contains XML templates that can be loaded into the Mitsuba renderer.

**Comment by inequation** [comment]
Nice, thanks!
